-- MySQL Script generated by MySQL Workbench
-- 03/21/16 17:24:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pro_biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pro_biblioteca` ;

-- -----------------------------------------------------
-- Schema pro_biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pro_biblioteca` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `pro_biblioteca` ;

-- -----------------------------------------------------
-- Table `pro_biblioteca`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`colonia` (
  `id_colonia` INT NOT NULL AUTO_INCREMENT,
  `nombre_colonia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_colonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`usuario` (
  `id_usuario` INT NOT NULL,
  `huella` BLOB NULL,
  `imagen_perfil` BLOB NULL,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `ape_pat` VARCHAR(45) NOT NULL,
  `ape_mat` VARCHAR(45) NOT NULL,
  `num_calle` VARCHAR(10) NOT NULL,
  `num_casa` VARCHAR(10) NULL,
  `calle_superior` VARCHAR(10) NULL,
  `calle_inferior` VARCHAR(10) NULL,
  `genero` VARCHAR(10) NULL,
  `fk_id_colonia` INT NOT NULL,
  `fk_id_estado` INT NOT NULL,
  `fk_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_colonia`
    FOREIGN KEY (`fk_id_colonia`)
    REFERENCES `pro_biblioteca`.`colonia` (`id_colonia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_estado`
    FOREIGN KEY (`fk_id_estado`)
    REFERENCES `pro_biblioteca`.`estado` (`id_estado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_localidad`
    FOREIGN KEY (`fk_id_localidad`)
    REFERENCES `pro_biblioteca`.`localidad` (`id_localidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_colonia_idx` ON `pro_biblioteca`.`usuario` (`fk_id_colonia` ASC);

CREATE INDEX `id_estado_idx` ON `pro_biblioteca`.`usuario` (`fk_id_estado` ASC);

CREATE INDEX `id_localidad_idx` ON `pro_biblioteca`.`usuario` (`fk_id_localidad` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`email` (
  `correo` VARCHAR(50) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`correo`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`email` (`fk_id_usuario` ASC);

CREATE UNIQUE INDEX `correo_UNIQUE` ON `pro_biblioteca`.`email` (`correo` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`telefono_casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`telefono_casa` (
  `tel_casa` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`tel_casa`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`telefono_casa` (`fk_id_usuario` ASC);

CREATE UNIQUE INDEX `tel_casa_UNIQUE` ON `pro_biblioteca`.`telefono_casa` (`tel_casa` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`telefono_celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`telefono_celular` (
  `tel_cel` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`tel_cel`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`telefono_celular` (`fk_id_usuario` ASC);

CREATE UNIQUE INDEX `tel_cel_UNIQUE` ON `pro_biblioteca`.`telefono_celular` (`tel_cel` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_carrera_UNIQUE` ON `pro_biblioteca`.`carrera` (`id_carrera` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`alumno` (
  `matricula` BIGINT(12) NOT NULL,
  `semestre` VARCHAR(15) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_carrera` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_carrera`
    FOREIGN KEY (`fk_id_carrera`)
    REFERENCES `pro_biblioteca`.`carrera` (`id_carrera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`alumno` (`fk_id_usuario` ASC);

CREATE INDEX `id_carrera_idx` ON `pro_biblioteca`.`alumno` (`fk_id_carrera` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`registro_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`registro_entrada` (
  `id_registro_entrada` INT NOT NULL AUTO_INCREMENT,
  `hora_entrada` TIME NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fk_matricula` BIGINT(12) NOT NULL,
  PRIMARY KEY (`id_registro_entrada`),
  CONSTRAINT `matricula`
    FOREIGN KEY (`fk_matricula`)
    REFERENCES `pro_biblioteca`.`alumno` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `matricula_idx` ON `pro_biblioteca`.`registro_entrada` (`fk_matricula` ASC);

CREATE UNIQUE INDEX `id_registro_entrada_UNIQUE` ON `pro_biblioteca`.`registro_entrada` (`id_registro_entrada` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`docente` (
  `rfc` VARCHAR(30) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`rfc`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`docente` (`fk_id_usuario` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`bibliotecario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`bibliotecario` (
  `rfc_bibliotecario` VARCHAR(30) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `id_login` VARCHAR(45) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`rfc_bibliotecario`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`bibliotecario` (`fk_id_usuario` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`clasificacion_dewey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`clasificacion_dewey` (
  `id_clasificacion_dewey` INT NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clasificacion_dewey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`material_bibliografico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`material_bibliografico` (
  `codigo_de_barra` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `num_paginas` INT NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `num_estante` INT NULL,
  `num_seccion` INT NULL,
  `fk_id_calisifacion_dewey` INT NOT NULL,
  PRIMARY KEY (`codigo_de_barra`),
  CONSTRAINT `id_clasificacion_dewey`
    FOREIGN KEY (`fk_id_calisifacion_dewey`)
    REFERENCES `pro_biblioteca`.`clasificacion_dewey` (`id_clasificacion_dewey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_clasificacion_dewey_idx` ON `pro_biblioteca`.`material_bibliografico` (`fk_id_calisifacion_dewey` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `edicion` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `num_tomo` VARCHAR(45) NULL,
  `fk_codigo_de_barra` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  CONSTRAINT `codigo_de_barra`
    FOREIGN KEY (`fk_codigo_de_barra`)
    REFERENCES `pro_biblioteca`.`material_bibliografico` (`codigo_de_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `codigo_de_barra_idx` ON `pro_biblioteca`.`libro` (`fk_codigo_de_barra` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`tesis` (
  `id_tesis` INT NOT NULL AUTO_INCREMENT,
  `carrera` VARCHAR(45) NOT NULL,
  `fk_codigo_de_barra` INT NOT NULL,
  PRIMARY KEY (`id_tesis`),
  CONSTRAINT `codigo_de_barra`
    FOREIGN KEY (`fk_codigo_de_barra`)
    REFERENCES `pro_biblioteca`.`material_bibliografico` (`codigo_de_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `codigo_de_barra_idx` ON `pro_biblioteca`.`tesis` (`fk_codigo_de_barra` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`revista` (
  `id_revista` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(45) NULL,
  `edicion` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `fk_codigo_de_barra` INT NOT NULL,
  PRIMARY KEY (`id_revista`),
  CONSTRAINT `codigo_de_barra`
    FOREIGN KEY (`fk_codigo_de_barra`)
    REFERENCES `pro_biblioteca`.`material_bibliografico` (`codigo_de_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `codigo_de_barra_idx` ON `pro_biblioteca`.`revista` (`fk_codigo_de_barra` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`prestamos` (
  `id_prestamos` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrega` DATETIME NOT NULL,
  `hora_actual` TIME NOT NULL,
  `fecha_actual` DATE NOT NULL,
  `fk_rfc_bibliotecario` VARCHAR(30) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_prestamos`),
  CONSTRAINT `rfc_bibliotecario`
    FOREIGN KEY (`fk_rfc_bibliotecario`)
    REFERENCES `pro_biblioteca`.`bibliotecario` (`rfc_bibliotecario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `pro_biblioteca`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `rfc_bibliotecario_idx` ON `pro_biblioteca`.`prestamos` (`fk_rfc_bibliotecario` ASC);

CREATE INDEX `id_usuario_idx` ON `pro_biblioteca`.`prestamos` (`fk_id_usuario` ASC);

CREATE UNIQUE INDEX `id_prestamos_UNIQUE` ON `pro_biblioteca`.`prestamos` (`id_prestamos` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`detalle_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`detalle_prestamo` (
  `id_detallte_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fk_id_prestamos` INT NOT NULL,
  `fk_codigo_de_barra` INT NOT NULL,
  PRIMARY KEY (`id_detallte_prestamo`),
  CONSTRAINT `codigo_de_barra`
    FOREIGN KEY (`fk_codigo_de_barra`)
    REFERENCES `pro_biblioteca`.`material_bibliografico` (`codigo_de_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_prestamos`
    FOREIGN KEY (`fk_id_prestamos`)
    REFERENCES `pro_biblioteca`.`prestamos` (`id_prestamos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `codigo_de_barra_idx` ON `pro_biblioteca`.`detalle_prestamo` (`fk_codigo_de_barra` ASC);

CREATE INDEX `id_prestamos_idx` ON `pro_biblioteca`.`detalle_prestamo` (`fk_id_prestamos` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`deuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`deuda` (
  `id_deuda` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `dias_transcurridos` VARCHAR(10) NOT NULL,
  `total` VARCHAR(10) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_deuda`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_deuda_UNIQUE` ON `pro_biblioteca`.`deuda` (`id_deuda` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`devolucion` (
  `id_devolucion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado_prestamo` VARCHAR(70) NOT NULL,
  `fk_rfc_bibliotecario` VARCHAR(30) NOT NULL,
  `fk_id_prestamos` INT NOT NULL,
  `fk_id_deuda` INT NOT NULL,
  PRIMARY KEY (`id_devolucion`),
  CONSTRAINT `rfc_bibliotecario`
    FOREIGN KEY (`fk_rfc_bibliotecario`)
    REFERENCES `pro_biblioteca`.`bibliotecario` (`rfc_bibliotecario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_prestamos`
    FOREIGN KEY (`fk_id_prestamos`)
    REFERENCES `pro_biblioteca`.`prestamos` (`id_prestamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_deuda`
    FOREIGN KEY (`fk_id_deuda`)
    REFERENCES `pro_biblioteca`.`deuda` (`id_deuda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `rfc_bibliotecario_idx` ON `pro_biblioteca`.`devolucion` (`fk_rfc_bibliotecario` ASC);

CREATE INDEX `id_prestamos_idx` ON `pro_biblioteca`.`devolucion` (`fk_id_prestamos` ASC);

CREATE INDEX `id_deuda_idx` ON `pro_biblioteca`.`devolucion` (`fk_id_deuda` ASC);

CREATE UNIQUE INDEX `id_devolucion_UNIQUE` ON `pro_biblioteca`.`devolucion` (`id_devolucion` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`detalle_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`detalle_devolucion` (
  `id_detalle_devolucion` INT NOT NULL AUTO_INCREMENT,
  `fk_id_devolucion` INT NOT NULL,
  `fk_codigo_de_barra` INT NOT NULL,
  PRIMARY KEY (`id_detalle_devolucion`),
  CONSTRAINT `codigo_de_barra`
    FOREIGN KEY (`fk_codigo_de_barra`)
    REFERENCES `pro_biblioteca`.`material_bibliografico` (`codigo_de_barra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_devolucion`
    FOREIGN KEY (`fk_id_devolucion`)
    REFERENCES `pro_biblioteca`.`devolucion` (`id_devolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `codigo_de_barra_idx` ON `pro_biblioteca`.`detalle_devolucion` (`fk_codigo_de_barra` ASC);

CREATE INDEX `id_devolucion_idx` ON `pro_biblioteca`.`detalle_devolucion` (`fk_id_devolucion` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `nombre_turno` VARCHAR(45) NULL,
  PRIMARY KEY (`id_turno`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_turno_UNIQUE` ON `pro_biblioteca`.`turno` (`id_turno` ASC);


-- -----------------------------------------------------
-- Table `pro_biblioteca`.`turno_bibliotecario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_biblioteca`.`turno_bibliotecario` (
  `id_turno_bibliotecario` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `fk_id_turno` INT NOT NULL,
  `fk_rfc_bibliotecario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_turno_bibliotecario`),
  CONSTRAINT `id_turno`
    FOREIGN KEY (`fk_id_turno`)
    REFERENCES `pro_biblioteca`.`turno` (`id_turno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rfc_bibliotecario`
    FOREIGN KEY (`fk_rfc_bibliotecario`)
    REFERENCES `pro_biblioteca`.`bibliotecario` (`rfc_bibliotecario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `id_turno_idx` ON `pro_biblioteca`.`turno_bibliotecario` (`fk_id_turno` ASC);

CREATE INDEX `rfc_bibliotecario_idx` ON `pro_biblioteca`.`turno_bibliotecario` (`fk_rfc_bibliotecario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
