/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class intFrmPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form intFrmPrestamo
     */
    public intFrmPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedorUsuarios = new javax.swing.JPanel();
        lblTituloUsuario = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        pnlHuella = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        pnlFotoPerfil = new javax.swing.JPanel();
        lblApellidosUsuario = new javax.swing.JLabel();
        txtApellidosUsuario = new javax.swing.JTextField();
        pnlMaterialBibliografico = new javax.swing.JPanel();
        lblTituloMaterial = new javax.swing.JLabel();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        btnInsertarPrestamo = new javax.swing.JButton();
        pnd = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        pnlValidacion = new javax.swing.JPanel();
        lblValidacion = new javax.swing.JLabel();
        lblNumeroPrestamo = new javax.swing.JLabel();
        txlNumeroPrestamo = new javax.swing.JLabel();
        lblBibliotecario = new javax.swing.JLabel();
        txlBibliotecario = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        txlFechaActual = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        txlHora = new javax.swing.JLabel();
        cbxNotificacion = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnlHerramientas = new javax.swing.JPanel();
        btnNuevoCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscarEditar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlContenedorUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTituloUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTituloUsuario.setText("Usuario");

        lblFechaEntrega.setText("Matricula:");

        pnlHuella.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huella", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        javax.swing.GroupLayout pnlHuellaLayout = new javax.swing.GroupLayout(pnlHuella);
        pnlHuella.setLayout(pnlHuellaLayout);
        pnlHuellaLayout.setHorizontalGroup(
            pnlHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlHuellaLayout.setVerticalGroup(
            pnlHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblNombreUsuario.setText("Nombre:");

        pnlFotoPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        javax.swing.GroupLayout pnlFotoPerfilLayout = new javax.swing.GroupLayout(pnlFotoPerfil);
        pnlFotoPerfil.setLayout(pnlFotoPerfilLayout);
        pnlFotoPerfilLayout.setHorizontalGroup(
            pnlFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlFotoPerfilLayout.setVerticalGroup(
            pnlFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblApellidosUsuario.setText("Apellidos:");

        javax.swing.GroupLayout pnlContenedorUsuariosLayout = new javax.swing.GroupLayout(pnlContenedorUsuarios);
        pnlContenedorUsuarios.setLayout(pnlContenedorUsuariosLayout);
        pnlContenedorUsuariosLayout.setHorizontalGroup(
            pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                        .addComponent(lblFechaEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                        .addComponent(lblApellidosUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidosUsuario))
                    .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                        .addComponent(lblNombreUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenedorUsuariosLayout.setVerticalGroup(
            pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorUsuariosLayout.createSequentialGroup()
                        .addGroup(pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaEntrega)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreUsuario)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidosUsuario)
                            .addComponent(txtApellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlMaterialBibliografico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTituloMaterial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTituloMaterial.setText("Material Bibliográfico");

        lblCodigoBarras.setText("Código de Barras:");

        btnInsertarPrestamo.setText("Insertar");

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnd.setViewportView(tblMaterial);

        javax.swing.GroupLayout pnlMaterialBibliograficoLayout = new javax.swing.GroupLayout(pnlMaterialBibliografico);
        pnlMaterialBibliografico.setLayout(pnlMaterialBibliograficoLayout);
        pnlMaterialBibliograficoLayout.setHorizontalGroup(
            pnlMaterialBibliograficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                .addGroup(pnlMaterialBibliograficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                        .addGroup(pnlMaterialBibliograficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTituloMaterial))
                            .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblCodigoBarras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInsertarPrestamo)))
                        .addGap(0, 323, Short.MAX_VALUE))
                    .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnd)))
                .addContainerGap())
        );
        pnlMaterialBibliograficoLayout.setVerticalGroup(
            pnlMaterialBibliograficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialBibliograficoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMaterial)
                .addGap(22, 22, 22)
                .addGroup(pnlMaterialBibliograficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarPrestamo))
                .addGap(18, 18, 18)
                .addComponent(pnd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlValidacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblValidacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValidacion.setText("Validación");

        lblNumeroPrestamo.setText("Número de prestamo:");

        lblBibliotecario.setText("Nombre Bibliotecario:");

        lblFechaActual.setText("Fecha:");

        lblHora.setText("Hora:");

        cbxNotificacion.setText("Notificación");

        jLabel1.setText("Fecha de entrega:");

        javax.swing.GroupLayout pnlValidacionLayout = new javax.swing.GroupLayout(pnlValidacion);
        pnlValidacion.setLayout(pnlValidacionLayout);
        pnlValidacionLayout.setHorizontalGroup(
            pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidacionLayout.createSequentialGroup()
                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblValidacion))
                    .addGroup(pnlValidacionLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlValidacionLayout.createSequentialGroup()
                                .addComponent(lblNumeroPrestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txlNumeroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(lblFechaActual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txlFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlValidacionLayout.createSequentialGroup()
                                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBibliotecario)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txlBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlValidacionLayout.createSequentialGroup()
                                .addComponent(lblHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxNotificacion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlValidacionLayout.setVerticalGroup(
            pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValidacion)
                .addGap(18, 18, 18)
                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroPrestamo)
                        .addComponent(txlNumeroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHora)
                        .addComponent(txlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaActual)
                        .addComponent(txlFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBibliotecario)
                        .addComponent(txlBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxNotificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHerramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevoCancelar.setText("Nuevo");

        btnGuardar.setText("Guardar");

        btnBuscarEditar.setText("Editar");

        btnImprimir.setText("Imprimir");

        javax.swing.GroupLayout pnlHerramientasLayout = new javax.swing.GroupLayout(pnlHerramientas);
        pnlHerramientas.setLayout(pnlHerramientasLayout);
        pnlHerramientasLayout.setHorizontalGroup(
            pnlHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHerramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarEditar)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHerramientasLayout.setVerticalGroup(
            pnlHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHerramientasLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnlHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscarEditar)
                    .addComponent(btnImprimir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedorUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMaterialBibliografico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMaterialBibliografico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnInsertarPrestamo;
    private javax.swing.JButton btnNuevoCancelar;
    private javax.swing.JCheckBox cbxNotificacion;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidosUsuario;
    private javax.swing.JLabel lblBibliotecario;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNumeroPrestamo;
    private javax.swing.JLabel lblTituloMaterial;
    private javax.swing.JLabel lblTituloUsuario;
    private javax.swing.JLabel lblValidacion;
    private javax.swing.JScrollPane pnd;
    private javax.swing.JPanel pnlContenedorUsuarios;
    private javax.swing.JPanel pnlFotoPerfil;
    private javax.swing.JPanel pnlHerramientas;
    private javax.swing.JPanel pnlHuella;
    private javax.swing.JPanel pnlMaterialBibliografico;
    private javax.swing.JPanel pnlValidacion;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JLabel txlBibliotecario;
    private javax.swing.JLabel txlFechaActual;
    private javax.swing.JLabel txlHora;
    private javax.swing.JLabel txlNumeroPrestamo;
    private javax.swing.JTextField txtApellidosUsuario;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
